language: swift

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.3beta
      env: TOOL=xcodebuild

    - os: osx
      compiler: clang
      osx_image: xcode9.2
      env: TOOL=xcodebuild

script:
    - xcodebuild -project GoofySwift.xcodeproj -target GoofySwift;

notifications:
    on_success: never
    on_failure: always
